// <auto-generated />
using System;
using BankFinderAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankFinderAPI.Migrations
{
    [DbContext(typeof(BanksDbContext))]
    [Migration("20211115215500_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("BankFinderAPI.Models.DaneAdresowe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("KodPocztowy")
                        .HasColumnType("text");

                    b.Property<string>("KodPocztySkrytkiPocztowej")
                        .HasColumnType("text");

                    b.Property<string>("Kraj")
                        .HasColumnType("text");

                    b.Property<string>("Miejscowosc")
                        .HasColumnType("text");

                    b.Property<int>("NrSkrytkiPocztowej")
                        .HasColumnType("int");

                    b.Property<DateTime>("NumerBudynku")
                        .HasColumnType("datetime");

                    b.Property<string>("Poczta")
                        .HasColumnType("text");

                    b.Property<string>("Powiat")
                        .HasColumnType("text");

                    b.Property<string>("Ulica")
                        .HasColumnType("text");

                    b.Property<string>("Wojewodztwo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DaneAdresowe");
                });
#pragma warning restore 612, 618
        }
    }
}
