// <auto-generated />
using System;
using BankFinderAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankFinderAPI.Migrations
{
    [DbContext(typeof(BanksDbContext))]
    [Migration("20211122202525_ChangeSortCodeFieldType")]
    partial class ChangeSortCodeFieldType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("BankFinderAPI.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BuildingNumber")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<int>("PoBoxNumber")
                        .HasColumnType("int");

                    b.Property<string>("PoBoxZipCode")
                        .HasColumnType("text");

                    b.Property<string>("Post")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("Voivodeship")
                        .HasColumnType("text");

                    b.Property<string>("ZpiCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("BankFinderAPI.Models.BicCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("SortCodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SortCodeId");

                    b.ToTable("BicCode");
                });

            modelBuilder.Entity("BankFinderAPI.Models.SortCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("CodeName")
                        .HasColumnType("text");

                    b.Property<DateTime>("GenerationDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("SortCode");
                });

            modelBuilder.Entity("BankFinderAPI.Models.BicCode", b =>
                {
                    b.HasOne("BankFinderAPI.Models.SortCode", "SortCode")
                        .WithMany("BicCodes")
                        .HasForeignKey("SortCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SortCode");
                });

            modelBuilder.Entity("BankFinderAPI.Models.SortCode", b =>
                {
                    b.Navigation("BicCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
